runtime: nodejs14

handlers:
  - url: /
    secure: always
    static_files: dist/index.html
    upload: dist/.*

  - url: /api/.*
    secure: always
    redirect_http_response_code: 301
    script: auto

  - url: /.*
    secure: always
    static_files: dist/index.html
    upload: dist/.*