runtime: nodejs14

handlers:
  - url: /
    secure: always
    static_files: build/index.html
    upload: build/index.html

  - url: /
    static_dir: build

  - url: /api/.*
    secure: always
    redirect_http_response_code: 301
    script: auto