name: Deploy MEB Resources Backend
on: workflow_dispatch

jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.gcp_credentials }}
      - name: GCP API Deploy
        uses: google-github-actions/deploy-appengine@v1
        with:
          working_directory: ./backend
          deliverables: api.yaml
      - name: GCP Dispatch Deploy
        uses: google-github-actions/deploy-appengine@v1
        with:
          working_directory: .
          deliverables: dispatch.yaml
