name: Deploy MEB Resources Frontend
on: workflow_dispatch

jobs:
  deploy:
    name: Deploy React Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node Env
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Build
        run: |
          cd ./frontend
          npm install
          npm run build
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.gcp_credentials }}
      - name: GCP React Client Deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          working_directory: ./frontend
          deliverables: client.yaml
