# .github/workflows/deploy.yaml

name: Deploy to Google App Engine
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/deploy-appengine@main
        with:
          deliverables: app.yaml
          credentials: ${{ secrets.gcp_credentials }}
