# .github/workflows/deploy.yaml

name: Deploy MEB Resources
on:
  push:
    branches:
      - main

jobs:
  deploy_frontend:
    name: MEB Resources frontend deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Build 
        run: |
           cd ./frontend
           npm install
           npm run build
      - id: upload-files
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
          path: ../build
          destination: meb-resources

  deploy_backend:
    name: MEB Resources backend deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/deploy-appengine@main
        with:
          working_directory: ./backend
          credentials: ${{ secrets.gcp_credentials }}
