# .github/workflows/deploy.yaml

name: Deploy to Google App Engine
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: meb resources backend deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Build 
        run: |
           cd backend
      - uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
